### ISSUE TITLE
test.lua out of memory

### ISSUE THREAD

**Issue by SkyeFromKindergarten** [davidstutz/torch-volumetric-nnup#1]
I did all the steps above and then I run test.lua it says out of memory as shown below:

lxm@ubuntuPG:~/gy/daml-shape-completion/torch-volumetric-nnup$ th test.lua
   8
   2
  40
  90
 160
[torch.LongStorage of size 5]

  8
  2
 10
 10
 10
[torch.LongStorage of size 5]

THCudaCheck FAIL file=/home/lxm/torch/extra/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
/home/lxm/torch/install/bin/luajit: /home/lxm/torch/install/share/lua/5.1/nn/utils.lua:11: cuda runtime error (2) : out of memory at /home/lxm/torch/extra/cutorch/lib/THC/generic/THCStorage.cu:66
stack traceback:
	[C]: in function 'resize'
	/home/lxm/torch/install/share/lua/5.1/nn/utils.lua:11: in function 'torch_Storage_type'
	/home/lxm/torch/install/share/lua/5.1/nn/utils.lua:57: in function 'recursiveType'
	/home/lxm/torch/install/share/lua/5.1/nn/Module.lua:160: in function 'type'
	/home/lxm/torch/install/share/lua/5.1/nn/utils.lua:45: in function 'recursiveType'
	/home/lxm/torch/install/share/lua/5.1/nn/utils.lua:41: in function 'recursiveType'
	/home/lxm/torch/install/share/lua/5.1/nn/Module.lua:160: in function 'cuda'
	test.lua:20: in main chunk
	[C]: in function 'dofile'
	.../lxm/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

My GPU has enough memory, so I don't know how can I solve this problem?  Actually I am trying to run your another work,  Weakly Supervised Shape Completion.  

Looking forward to your reply.

**Comment by davidstutz** [comment]
Sorry for the late reply. Did you solve it by now (because you closed the issue), or does the problem persist?

**Comment by SkyeFromKindergarten** [comment]
yeah that problem  occurred because of my own mistake, it's been solved now. Thanks for your attention.





--

郭 燕
厦门大学 信息科学与技术学院
智能科学系 2018级研究生
联系方式：18805926283

At 2018-11-29 23:47:06, "David Stutz" <notifications@github.com> wrote:


Sorry for the late reply. Did you solve it by now (because you closed the issue), or does the problem persist?
